# Generated by Django 4.1.2 on 2022-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhut_app', '0002_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=25)),
                ('nprice', models.IntegerField()),
                ('ndes', models.CharField(max_length=100)),
                ('nimage', models.FileField(upload_to='foodhut_app/static/non_veg')),
            ],
        ),
        migrations.CreateModel(
            name='vegmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=25)),
                ('vprice', models.IntegerField()),
                ('vdes', models.CharField(max_length=100)),
                ('vimage', models.FileField(upload_to='foodhut_app/static/veg')),
            ],
        ),
    ]
