# Generated by Django 4.1.2 on 2022-11-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhut_app', '0003_nonmodel_vegmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonmodel',
            old_name='nname',
            new_name='nitem',
        ),
        migrations.RenameField(
            model_name='vegmodel',
            old_name='vname',
            new_name='vitem',
        ),
    ]
