# Generated by Django 4.1.2 on 2022-11-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhut_app', '0006_alter_adddetailsmodel_rimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddetailsmodel',
            name='rimage',
            field=models.FileField(upload_to='foodhut_app/static'),
        ),
    ]
